[package]
name = "c-compiler"
version = "0.1.0"
authors = ["hidexir <goto_hideaki@abema.tv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
